"""
Backfills gradeNorm and englishMatn into a prod english-mxbai index
that was either transferred from dev or rebuilt without those fields.

Sources:
  - gradeNorm: copied from dev arabic-openai via matchingArabicURN
               (same normalization logic as normalize_grades.py)
  - englishMatn: loaded from english_matn_map.json (24MB, generated by
                 extract_english_matn.py — copy to prod server first)

Safe to re-run: skips docs that already have gradeNorm set.

Usage (inside prod container, with english_matn_map.json copied over):
    python3 /code/tests/backfill_prod_fields.py

Or against dev:
    docker exec search-web-1 python3 /code/tests/backfill_prod_fields.py
"""
import os, json, time
from concurrent.futures import ThreadPoolExecutor, as_completed
from elasticsearch import Elasticsearch
from elasticsearch.helpers import scan as es_scan

TARGET_INDEX = "english-mxbai"
MATN_MAP_FILE = "/code/english_matn_map.json"
THREADS = 16

NORM_MAP = {
    "sahih": "Sahih", "صحيح": "Sahih",
    "hasan": "Hasan", "حسن": "Hasan",
    "hasan sahih": "Hasan", "sahih hasan": "Hasan",
    "da'if": "Da'if", "daif": "Da'if", "weak": "Da'if", "ضعيف": "Da'if",
    "maudu'": "Maudu'", "maudu": "Maudu'", "fabricated": "Maudu'", "موضوع": "Maudu'",
}

def normalize(raw):
    if not raw:
        return None
    cleaned = raw.strip().strip("]").strip()
    # strip JSON wrapper [{"grade":...}]
    if cleaned.startswith("[") or cleaned.startswith("{"):
        import re
        m = re.search(r'"grade"\s*:\s*"([^"]+)"', cleaned)
        cleaned = m.group(1) if m else cleaned
    cleaned = cleaned.lower().strip()
    # strip publisher suffixes like "(Al-Albani)"
    cleaned = re.sub(r'\s*\([^)]+\)', '', cleaned).strip()
    if cleaned in NORM_MAP:
        return NORM_MAP[cleaned]
    for k, v in NORM_MAP.items():
        if cleaned.startswith(k):
            return v
    return None

import re

es = Elasticsearch(
    os.environ.get("ES_HOST", "http://172.31.250.10:9200"),
    basic_auth=("elastic", os.environ["ELASTIC_PASSWORD"]),
    request_timeout=60,
)

# ── Load englishMatn map ───────────────────────────────────────────────────────
matn_map = {}
if os.path.exists(MATN_MAP_FILE):
    print(f"Loading {MATN_MAP_FILE}...")
    with open(MATN_MAP_FILE, encoding="utf-8") as f:
        matn_map = json.load(f)   # {urn_str: {"matn": ..., "hadithNumber": ...}}
    print(f"  {len(matn_map):,} entries")
else:
    print(f"WARNING: {MATN_MAP_FILE} not found — englishMatn will not be backfilled")

# ── Build gradeNorm lookup from arabic-openai ─────────────────────────────────
print("Building gradeNorm lookup from arabic-openai...")
t0 = time.time()
ar_urn_to_norm = {}

for hit in es_scan(es, index="arabic-openai",
        _source=["arabicURN", "gradeEnglish", "gradeArabic", "gradeNorm"],
        query={"query": {"match_all": {}}}, size=500):
    s    = hit["_source"]
    urn  = s.get("arabicURN")
    norm = s.get("gradeNorm") or normalize(s.get("gradeEnglish") or s.get("gradeArabic"))
    if urn and norm:
        ar_urn_to_norm[urn] = norm

print(f"  {len(ar_urn_to_norm):,} Arabic URNs with grades ({time.time()-t0:.0f}s)")

# ── Scan target index and build update pairs ──────────────────────────────────
print(f"Scanning {TARGET_INDEX}...")
t0 = time.time()
updates = []    # [(doc_id, grade_norm, english_matn)]

BUKHARI_MUSLIM = {"bukhari", "muslim"}

for hit in es_scan(es, index=TARGET_INDEX,
        _source=["urn", "matchingArabicURN", "collection", "gradeNorm", "grade",
                 "arabicGrade", "englishMatn"],
        query={"query": {"match_all": {}}}, size=500):
    s      = hit["_source"]
    doc_id = hit["_id"]
    urn    = str(s.get("urn", ""))

    # gradeNorm
    existing = s.get("gradeNorm")
    if not existing:
        norm = normalize(s.get("grade") or s.get("arabicGrade"))
        if not norm:
            coll    = s.get("collection", "")
            ar_urn  = s.get("matchingArabicURN")
            if coll in BUKHARI_MUSLIM:
                norm = "Sahih"
            elif ar_urn:
                norm = ar_urn_to_norm.get(ar_urn)
        grade_norm = norm or "Uncategorized"
    else:
        grade_norm = existing

    # englishMatn
    existing_matn = s.get("englishMatn") or ""
    if not existing_matn and urn in matn_map:
        english_matn = matn_map[urn].get("matn", "")
    else:
        english_matn = existing_matn

    # Only include in updates if something actually changed
    needs_grade = not s.get("gradeNorm")
    needs_matn  = not existing_matn and bool(english_matn)
    if needs_grade or needs_matn:
        updates.append((doc_id, grade_norm, english_matn))

print(f"  {len(updates):,} docs need updates ({time.time()-t0:.0f}s)")
if not updates:
    print("Nothing to do.")
    raise SystemExit(0)

# ── Apply updates in parallel ─────────────────────────────────────────────────
# english-mxbai uses semantic_text — must use individual es.update() calls,
# NOT bulk, because bulk doc-partial updates are blocked by ES on semantic_text indexes.
print(f"Updating {TARGET_INDEX} with {THREADS} threads...")
t0 = time.time()
done = err = 0

def _do_update(args):
    doc_id, grade_norm, english_matn = args
    patch = {"gradeNorm": grade_norm}
    if english_matn:
        patch["englishMatn"] = english_matn
    es.update(index=TARGET_INDEX, id=doc_id, body={"doc": patch})
    return 1

with ThreadPoolExecutor(max_workers=THREADS) as pool:
    futures = {pool.submit(_do_update, u): u for u in updates}
    for fut in as_completed(futures):
        try:
            done += fut.result()
        except Exception as e:
            err += 1
            if err <= 5:
                print(f"  update error: {e}")
        if done % 5000 == 0 and done > 0:
            elapsed = time.time() - t0
            print(f"  {done:,}/{len(updates):,} | {done/elapsed:.0f} doc/s | errors={err}")

print(f"\nDone: {done:,} updated, {err} errors | {time.time()-t0:.0f}s")
